#!/bin/bash

set -ex

apt-get update
apt-get -y install python-pip

dpkg -i $CHARM_DIR/files/influxdb_0.10.0-1_amd64.deb

cp /etc/influxdb/influxdb.conf \
   /etc/influxdb/influxdb.example.conf

pip install --no-index \
    --find-links=file://$CHARM_DIR/files -r files/requirements.txt

juju-log "Configuring graphite interface"
sed -i "s|DB_PORT|8217|g" $CHARM_DIR/files/influxdb.conf
cp $CHARM_DIR/files/influxdb.conf /etc/influxdb/influxdb.conf
# cp $CHARM_DIR/files/influxdb.conf /etc/opt/influxdb/shared/
open-port 8083
open-port 8086
