#!/bin/bash
set -ex
sudo service influxdb restart

for n in $(seq 30); do
    nc -z localhost 8217 && break
    if [ $n -lt 30 ]; then
        echo "Service not running..... wait 10s"
    fi
    sleep 2
done

